service: version1 

provider:
  name: aws
  runtime: nodejs18.x 
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 30
  deploymentBucket:
    name: serverless-deployment-bucket-1231315
  environment:
    NODE_ENV: ${self:provider.stage}
  tags:
    Project: "LambdaCode"
    Environment: ${self:provider.stage}

functions:
  functionA:
    handler: handler.functionA
    events:
      - httpApi:
          path: /version1/fA  # Mantendo alinhado com o API Gateway
          method: POST
  functionB:
    handler: handler.functionB
    events:
      - httpApi:
          path: /version1/fB  # Mantendo alinhado com o API Gateway
          method: POST

plugins:
  - serverless-offline  # Para rodar localmente

