service: version1

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 30
  deploymentBucket:
    name: serverless-deployment-bucket-1231315
  environment:
    NODE_ENV: ${self:provider.stage}
  tags:
    Project: "LambdaCode"
    Environment: ${self:provider.stage}

functions:
  functionA:
    handler: handler.functionA
    events:
      - http:
          path: version1/functionA
          method: GET
  functionB:
    handler: handler.functionB
    events:
      - http:
          path: version1/functionB
          method: POST

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.mycompany.com"
    basePath: "${self:service}-${self:provider.stage}"
    stage: ${self:provider.stage}
