service: version1

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 30
  deploymentBucket:
    name: serverless-deployment-bucket-12313156
  environment:
    NODE_ENV: ${self:provider.stage}
  tags:
    Project: "LambdaCode"
    Environment: ${self:provider.stage}

functions:
  functionA:
    handler: handler.functionA
    events:
      - http:
          path: version1/functionA
          method: GET
  functionB:
    handler: handler.functionB
    events:
      - http:
          path: version1/functionB
          method: POST

