service: version2

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 30
  deploymentBucket:
    name: serverless-deployment-bucket-1231315
  environment:
    NODE_ENV: ${self:provider.stage}
  tags:
    Project: "LambdaCode"
    Environment: ${self:provider.stage}

functions:
  functionX:
    handler: handler.functionX
    events:
      - http:
          path: functionX
          method: GET
  functionY:
    handler: handler.functionY
    events:
      - http:
          path: functionY
          method: POST

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.mycompany.com"
    basePath: "${self:service}-${self:provider.stage}"
    stage: ${self:provider.stage}
