name: Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      microservice:
        description: "Select the microservice (e.g., version1, version2, version3)"
        required: true
        type: choice
        options:
          - version1
          - version2
          - version3
      function:
        description: "Select the Lambda function to deploy (inside the selected microservice)"
        required: true
      environment:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-1

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Check if function exists
        id: check-function
        run: |
          FUNCTION_NAME="${{ inputs.function }}"
          MICRO_SERVICE="${{ inputs.microservice }}"
          STAGE="${{ inputs.environment }}"
          EXISTING_FUNCTION=$(aws lambda get-function --function-name "$MICRO_SERVICE-$FUNCTION_NAME-$STAGE" --query 'Configuration.FunctionArn' --output text || echo "not_found")

          if [[ "$EXISTING_FUNCTION" == "not_found" ]]; then
            echo "Function does not exist. Deploying full service..."
            echo "DEPLOY_FULL_SERVICE=true" >> $GITHUB_ENV
          else
            echo "Function exists. Deploying only the function..."
            echo "DEPLOY_FULL_SERVICE=false" >> $GITHUB_ENV
          fi

      - name: Deploy Full Service (if function does not exist)
        if: env.DEPLOY_FULL_SERVICE == 'true'
        run: |
          cd ${{ github.workspace }}/service/${{ inputs.microservice }}
          serverless deploy --stage ${{ inputs.environment }}

      - name: Deploy Single Function (if function exists)
        if: env.DEPLOY_FULL_SERVICE == 'false'
        run: |
          cd ${{ github.workspace }}/service/${{ inputs.microservice }}
          serverless deploy function -f ${{ inputs.function }} --stage ${{ inputs.environment }}
