name: Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      microservice:
        description: 'Choose the microservice (version1, version2, version3)'
        required: true
        type: choice
        options:
          - version1
          - version2
          - version3
      function:
        description: 'Choose the function to deploy'
        required: true
        type: choice
        options:
          - functionA
          - functionB
      environment:
        description: 'Choose environment (dev, stg, prod)'
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Serverless Framework
        run: npm i -g serverless@3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-1
      
      ##debug step
      - name: PWD in current directory
        run: pwd 

      - name: LS in current directory
        run: ls .

      - name: Deploy Lambda Function
        if: false
        run: |
          cd ${{ github.workspace }}/service/${{ inputs.microservice }}
          serverless deploy function -f ${{ inputs.function }} --stage ${{ inputs.environment }}
